$(document).ready(function(){
  $("#cambiarRegistro").click(function(){
    $('#login').toggle();
    $('#registro').toggle();
  });
  $("#cambiarLogin").click(function(){
    $('#login').toggle();
    $('#registro').toggle();
  });
});
